### ISSUE TITLE
Stroke color

### ISSUE THREAD

**Issue by alaa7731** [RobertApikyan/SegmentedControl#2]
is there a way to change the stroke (border) color with the divider?

and thanks for your work, it's amazing

**Comment by RobertApikyan** [comment]
Hi again, thank you for positive feat back,
Sure there is some methods and attributes in order to change the stock color, but I'm not clearly understand what you meant by saying `color with the divider?`

This is what you can archive with this attributes
setSelectedStockColor = "#Purple"
setUnSelectedStockColor ="#Grey"
setSelectedBackgroundColor ="#Blue" 

If this is will not help, please provide more details for clarification 

![image](https://user-images.githubusercontent.com/17802092/37816548-ed0c4864-2e8c-11e8-87d4-2b06079e7db0.png)

**Comment by alaa7731** [comment]
oh okay great thank you, i didn't saw it as i was searching from strockColor, not stockColor.

what i meant with the the `divider` is the strockColor, the divider lines between elements

**Comment by RobertApikyan** [comment]
Will be changed to strockColor, it's typo

**Comment by alaa7731** [comment]
no problem, thank you for your effort man

**Comment by RobertApikyan** [comment]
Fixed typo stock -> stroke
compile 'com.github.RobertApikyan:SegmentedControl:release_1.0.2'
